fix: install deps for e2e tests in ci
OpenZeppelin/defender-sdk pull request #570
Opened 2024-09-23 18:01 UTC by MCarlomagno

# Summary
Adds step in CI for installing e2e folder dependencies

2024-09-23 18:05 UTC, tirumerla requested changes
added a comment, thanks

2024-09-23 18:05 UTC, tirumerla commented on .github/actions/prepare/action.yml
> +        cd e2e && pnpm install
You probably need to use frozen lock file instead of updating the lock file, Similar to install-deps.

2024-09-24 02:47 UTC, tirumerla commented on package.json
> +    "build": "nx run-many -t build --parallel=1 --output-style",
```suggestion
    "build": "nx run-many -t build --parallel=1 --output-style=static",
```

2024-09-24 02:47 UTC, tirumerla commented on package.json
> +    "build-test": "nx run-many -t style,build,test --projects=@openzeppelin/defender-base-client,*  --parallel=false --output-style",
```suggestion
    "build-test": "nx run-many -t style,build,test --projects=@openzeppelin/defender-base-client,*  --parallel=false --output-style=static",
```

2024-09-24 02:47 UTC, tirumerla commented on package.json
> +    "test": "nx run-many -t test --exclude=e2e --parallel=1 --output-style",
```suggestion
    "test": "nx run-many -t test --exclude=e2e --parallel=1 --output-style=static",
```

2024-09-24 02:48 UTC, tirumerla commented on package.json
> +    "build:changed": "nx affected:build --base=origin/main --skip-nx-cache --parallel=1 --output-style",
```suggestion
    "build:changed": "nx affected:build --base=origin/main --skip-nx-cache --parallel=1 --output-style=static",
```

2024-09-24 02:48 UTC, tirumerla commented on package.json
> +    "test:changed": "nx affected:test --base=origin/main --skip-nx-cache --parallel=1 --output-style",
```suggestion
    "test:changed": "nx affected:test --base=origin/main --skip-nx-cache --parallel=1 --output-style=static",
```

2024-09-27 19:53 UTC, tirumerla approved these changes
lgtm, thanks

2024-09-27 19:56 UTC, shahnami approved these changes

2024-09-27 19:56 UTC, merged